"""empty message

Revision ID: 632de7bba79d
Revises: None
Create Date: 2016-07-09 19:06:32.839672

"""

# revision identifiers, used by Alembic.
revision = '632de7bba79d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('google_credentials', sa.String(), nullable=True))
    op.alter_column('user', 'id',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('user', 'google_credentials')
    ### end Alembic commands ###
